server:
  port: 8080
spring:
  application:
    name: tmnphConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/phonzie07/configs
          password: naitsirch007
          username: phonzie07
          search-paths: '{application}'
          force-pull: true